import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, where, setDoc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),provider=new GoogleAuthProvider();
let targets={"校必修":30,"院必修":18,"專業必修":47,"專業選修":33},currentCurriculum=null,curricula=[];
const domains=["人文領域","藝術領域","社會領域","自然領域"];
const terms={"1-1":"一年級上學期","1-2":"一年級下學期","2-1":"二年級上學期","2-2":"二年級下學期","3-1":"三年級上學期","3-2":"三年級下學期","4-1":"四年級上學期","4-2":"四年級下學期"};
let student={id:"B11500001",name:"王小明",department:"旅館管理與廚藝創意系",program:"日間部四技",admissionYear:"115",courses:[
 {id:"GE101",name:"分類通識-音樂好好聽(藝術領域)",credits:2,category:"校必修",subCategory:"分類通識",domain:"藝術領域",term:"1-1",status:"done"},
 {id:"PE101",name:"體育(一)",credits:2,category:"校必修",term:"1-1",status:"done"},{id:"CH101",name:"應用中文(一)",credits:2,category:"校必修",term:"1-1",status:"done"},
 {id:"EN101",name:"應用英文(一)",credits:2,category:"校必修",term:"1-1",status:"failed",attemptTerm:"115-1"},{id:"CS101",name:"程式設計概論",credits:2,category:"院必修",term:"1-1",status:"missing"},
 {id:"HC101",name:"旅館事業概論",credits:2,category:"專業必修",term:"1-1",status:"done"},{id:"HC102",name:"餐旅安全與法規",credits:2,category:"專業必修",term:"1-1",status:"done"},
 {id:"HC103",name:"餐飲廚藝概論",credits:2,category:"專業必修",term:"1-1",status:"done"},{id:"HC104",name:"餐旅美學",credits:2,category:"專業選修",term:"1-1",status:"done"},
 {id:"TO101",name:"觀光產業概論",credits:2,category:"專業選修",term:"1-1",status:"done"},{id:"GE102",name:"分類通識-創意邏輯動動手(自然領域)",credits:2,category:"校必修",subCategory:"分類通識",domain:"自然領域",term:"1-2",status:"done"},
 {id:"PE102",name:"體育(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},{id:"CH102",name:"應用中文(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},
 {id:"EN102",name:"應用英文(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},{id:"AI101",name:"人工智慧概論",credits:2,category:"院必修",term:"1-2",status:"missing"},
 {id:"HC110",name:"房務管理",credits:2,category:"專業必修",term:"1-2",status:"missing"},{id:"HC111",name:"房務模擬實務",credits:2,category:"專業必修",term:"1-2",status:"missing"},
 {id:"X001",name:"國際禮儀",credits:2,category:"專業選修",term:"2-2",status:"done"},{id:"X002",name:"投資理財實務",credits:2,category:"專業選修",term:"2-1",status:"done"}
]};
const demoStudent=structuredClone(student);
let role="student",tab="timeline",selected=null,editingCurriculum=null;
const views=[...document.querySelectorAll(".view")],recognized=()=>student.courses.filter(c=>c.status==="done"||c.status==="classified");
function show(id){views.forEach(v=>v.classList.toggle("hidden",v.id!==id));scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>show(b.dataset.back));
studentEntry.onclick=()=>show("queryView");teacherEntry.onclick=loginAndOpenTeacher;
addStudentBtn.onclick=async()=>{await loadCurricula();fillCurriculumSelect();if(!curricula.length){alert("請先建立至少一份時序表。");curriculumDialog.showModal();return}studentDialog.showModal()};
curriculumBtn.onclick=async()=>{await loadCurricula();renderCurricula();curriculumDialog.showModal()};
queryForm.onsubmit=e=>{e.preventDefault();const ok=queryName.value.trim()===demoStudent.name&&queryStudentId.value.trim().toUpperCase()===demoStudent.id;queryError.textContent=ok?"":"學生查詢尚未連接正式資料；示範請使用王小明／B11500001。";if(ok){student=structuredClone(demoStudent);openStudent("student")}};
logoutBtn.onclick=async()=>{await signOut(auth);show("homeView")};

async function loginAndOpenTeacher(){
 try{
  const user=auth.currentUser||(await signInWithPopup(auth,provider)).user;
  const allowed=(await getDoc(doc(db,"authorizedUsers",user.email))).exists();
  if(!allowed){await signOut(auth);alert("此帳號尚未被加入老師／小幫手權限名單。");return}
  show("teacherView");await loadCurricula();await loadMyStudents(user.email);
 }catch(error){console.error(error);alert(error.code==="auth/popup-closed-by-user"?"已取消登入。":"登入或讀取資料失敗，請確認 Firebase 權限規則已發布。");}
}
async function loadMyStudents(email){
 studentList.innerHTML='<div class="loading-row">正在載入學生資料…</div>';
 const snapshot=await getDocs(query(collection(db,"students"),where("ownerEmail","==",email)));
 const rows=snapshot.docs.map(d=>({docId:d.id,...d.data()}));
 if(!rows.length){studentList.innerHTML='<div class="empty">目前尚未建立學生，請按右上角「新增學生」。</div>';return}
 studentList.innerHTML=rows.map((s,i)=>`<article class="student-row"><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.studentId)}｜${escapeHtml(s.department)}｜${escapeHtml(s.admissionYear)}學年度入學</p></div><button class="primary open-real" data-index="${i}">查看學分</button></article>`).join("");
 document.querySelectorAll(".open-real").forEach(b=>b.onclick=async()=>{student=rows[Number(b.dataset.index)];student.id=student.studentId;currentCurriculum=curricula.find(c=>c.docId===student.curriculumId)||null;if(currentCurriculum)targets=currentCurriculum.targets;student.courses=student.courses?.length?student.courses:structuredClone(currentCurriculum?.courses||[]);openStudent("teacher")});
}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

saveStudentBtn.onclick=async e=>{
 e.preventDefault();studentFormError.textContent="";
 const user=auth.currentUser,id=studentIdInput.value.trim().toUpperCase();
 if(!user||!id){studentFormError.textContent="請完整填寫資料。";return}
 try{
  const ref=doc(db,"students",`${user.uid}_${id}`);
  if((await getDoc(ref)).exists()){studentFormError.textContent="這個學號已經建立。";return}
  const curriculum=curricula.find(c=>c.docId===curriculumSelect.value);if(!curriculum){studentFormError.textContent="請選擇適用時序表。";return}
  await setDoc(ref,{studentId:id,name:studentNameInput.value.trim(),admissionYear:admissionYearInput.value.trim(),department:departmentInput.value.trim(),program:programInput.value.trim(),curriculumId:curriculum.docId,ownerEmail:user.email,courses:structuredClone(curriculum.courses||[]),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
  studentDialog.close();studentForm.reset();programInput.value="日間部四技";await loadMyStudents(user.email);
 }catch(error){console.error(error);studentFormError.textContent="新增失敗，請先發布最新版 Firestore 規則。"}
};
onAuthStateChanged(auth,user=>{logoutBtn.classList.toggle("hidden",!user);systemBadge.textContent=user?`已登入：${user.email}`:"Firebase測試版"});

async function loadCurricula(){const snap=await getDocs(collection(db,"curricula"));curricula=snap.docs.map(d=>({docId:d.id,...d.data()})).sort((a,b)=>String(b.admissionYear).localeCompare(String(a.admissionYear)))}
function fillCurriculumSelect(){curriculumSelect.innerHTML='<option value="">請選擇時序表</option>'+curricula.filter(c=>c.status==="ready").map(c=>`<option value="${c.docId}">${escapeHtml(c.admissionYear)}｜${escapeHtml(c.department)}｜${escapeHtml(c.program)}</option>`).join("")}
function renderCurricula(){curriculumList.innerHTML=curricula.length?curricula.map(c=>`<div class="curriculum-row"><div><strong>${escapeHtml(c.admissionYear)}學年度｜${escapeHtml(c.department)}｜${escapeHtml(c.program)}</strong><span>來源：${escapeHtml(c.sourceFileName||"未上傳")}｜課程${c.courses?.length||0}門</span></div><div class="curriculum-actions"><span class="status-chip ${c.status==="ready"?"ready":"pending"}">${c.status==="ready"?"已啟用":"待辨識"}</span><button type="button" class="small-button edit-curriculum" data-id="${c.docId}">課程確認</button>${c.status!=="ready"?`<button type="button" class="small-button replace-curriculum" data-id="${c.docId}">更換PDF</button><button type="button" class="small-button danger delete-curriculum" data-id="${c.docId}">刪除</button>`:""}</div></div>`).join(""):'<div class="empty">尚未建立時序表。</div>';document.querySelectorAll(".edit-curriculum").forEach(b=>b.onclick=()=>openCourseEditor(b.dataset.id));document.querySelectorAll(".replace-curriculum").forEach(b=>b.onclick=()=>replaceCurriculumPdf(b.dataset.id));document.querySelectorAll(".delete-curriculum").forEach(b=>b.onclick=()=>removeCurriculum(b.dataset.id))}
saveCurriculumBtn.onclick=async e=>{e.preventDefault();curriculumError.textContent="";try{const year=curriculumYear.value.trim(),department=curriculumDepartment.value.trim(),program=curriculumProgram.value.trim(),file=curriculumPdfInput.files[0];if(!year||!department||!program||!file){curriculumError.textContent="請完整填寫版本資料並選擇PDF。";return}if(file.type!=="application/pdf"){curriculumError.textContent="只接受PDF檔案。";return}const duplicate=curricula.some(c=>c.admissionYear===year&&c.department===department&&c.program===program);if(duplicate){curriculumError.textContent="相同入學年度、科系與學制的時序表已存在。";return}const curriculumTargets={"校必修":Number(schoolRequiredInput.value),"院必修":Number(collegeRequiredInput.value),"專業必修":Number(majorRequiredInput.value),"專業選修":Number(majorElectiveInput.value)},id=`${year}_${Date.now()}`;saveCurriculumBtn.disabled=true;saveCurriculumBtn.textContent="建立中…";await setDoc(doc(db,"curricula",id),{admissionYear:year,department,program,totalCredits:Number(totalCreditsInput.value),targets:curriculumTargets,courses:[],status:"pending",sourceFileName:file.name,sourceStored:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadCurricula();renderCurricula();fillCurriculumSelect();openCourseEditor(id)}catch(error){console.error(error);curriculumError.textContent="建立失敗，請確認Firestore規則已發布。"}finally{saveCurriculumBtn.disabled=false;saveCurriculumBtn.textContent="選取PDF並建立待辨識版本"}};
function openCourseEditor(id){editingCurriculum=curricula.find(c=>c.docId===id);if(!editingCurriculum)return;courseEditorTitle.textContent=`${editingCurriculum.admissionYear}｜${editingCurriculum.department}｜${editingCurriculum.program}`;courseImportText.value=(editingCurriculum.courses||[]).map(c=>`${c.term}｜${c.category}｜${c.name}｜${c.credits}`).join("\n");courseEditorError.textContent="";courseEditorDialog.showModal()}
async function replaceCurriculumPdf(id){const curriculum=curricula.find(c=>c.docId===id);if(!curriculum)return;const input=document.createElement("input");input.type="file";input.accept="application/pdf";input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.type!=="application/pdf"){alert("只接受PDF檔案。");return}try{await updateDoc(doc(db,"curricula",id),{sourceFileName:file.name,sourceStored:false,courses:[],status:"pending",updatedAt:serverTimestamp()});await loadCurricula();renderCurricula();openCourseEditor(id)}catch(error){console.error(error);alert("更換失敗，請確認Firestore規則已發布。")}};input.click()}
async function removeCurriculum(id){const curriculum=curricula.find(c=>c.docId===id);if(!curriculum||!confirm(`確定刪除「${curriculum.admissionYear}｜${curriculum.department}｜${curriculum.program}」？`))return;try{const used=await getDocs(query(collection(db,"students"),where("curriculumId","==",id)));if(!used.empty){alert("這份時序表已經綁定學生，不能刪除。請改用課程修改或建立新版本。");return}await deleteDoc(doc(db,"curricula",id));await loadCurricula();renderCurricula();fillCurriculumSelect()}catch(error){console.error(error);alert("刪除失敗，請確認你是管理者並已發布最新版規則。")}}
confirmCoursesBtn.onclick=async e=>{e.preventDefault();try{const allowed=new Set(Object.keys(targets)),lines=courseImportText.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),courses=lines.map((line,i)=>{const p=line.split(/[｜|]/).map(x=>x.trim());if(p.length!==4||!terms[p[0]]||!allowed.has(p[1])||!p[2]||!(Number(p[3])>0))throw new Error(`第${i+1}行格式錯誤`);const name=p[2],domain=(name.match(/\((人文|藝術|社會|自然)領域\)/)||[])[1];return{id:`C${i+1}`,term:p[0],category:p[1],name,credits:Number(p[3]),status:"missing",...(name.startsWith("分類通識-")?{subCategory:"分類通識",domain:domain?`${domain}領域`:null}:{})}});if(!courses.length)throw new Error("請至少建立一門課程");await updateDoc(doc(db,"curricula",editingCurriculum.docId),{courses,status:"ready",updatedAt:serverTimestamp()});courseEditorDialog.close();await loadCurricula();renderCurricula();fillCurriculumSelect()}catch(error){courseEditorError.textContent=error.message||"課程儲存失敗。"}};
function openStudent(r){role=r;tab="timeline";document.querySelectorAll(".teacher-only").forEach(e=>e.classList.toggle("hidden",r!=="teacher"));document.querySelectorAll(".tab").forEach(e=>e.classList.toggle("active",e.dataset.tab==="timeline"));termFilter.value="all";detailBack.onclick=()=>show(r==="teacher"?"teacherView":"queryView");render();show("detailView")}
function totals(){const out=Object.fromEntries(Object.keys(targets).map(k=>[k,0]));let ext=0;recognized().forEach(c=>{let value=c.credits;if(c.external){value=Math.max(0,Math.min(value,12-ext));ext+=value}if(c.category in out)out[c.category]+=value});return out}
function render(){const t=totals(),sum=Object.values(t).reduce((a,b)=>a+b,0);studentHeader.innerHTML=`<div><h2>${student.name}</h2><p>${student.id}｜${student.department}｜${student.program}｜${student.admissionYear}學年度入學</p></div><div class="progress-total"><span>目前已取得</span><strong>${sum} 學分</strong></div>`;creditSummary.innerHTML=Object.entries(targets).map(([n,max])=>`<article class="credit-card"><h3>${n}</h3><div class="credit-numbers"><strong>${t[n]}</strong><span>／${max} 學分</span></div><div class="meter"><span style="width:${Math.min(100,t[n]/max*100)}%"></span></div></article>`).join("");renderGeneral();renderExternal();renderCourses()}
function renderGeneral(){const cs=recognized().filter(c=>c.subCategory==="分類通識"),credits=cs.reduce((n,c)=>n+c.credits,0),missing=domains.filter(d=>!cs.some(c=>c.domain===d));generalEducationSummary.innerHTML=`<section class="special-card"><div class="special-heading"><div><h3>分類通識領域檢核</h3><small>併入校必修；四領域各至少1門，再任選2門</small></div><strong>${credits}／12 學分</strong></div><div class="domain-grid">${domains.map(d=>{const count=cs.filter(c=>c.domain===d).length;return `<div class="domain-item ${count?"done":"missing"}"><strong>${d}</strong><span>${count?`已完成 ${count} 門`:"尚未完成"}</span></div>`}).join("")}</div>${missing.length?`<div class="warning-box">⚠ 尚缺領域：${missing.join("、")}</div>`:`<div class="success-box">✓ 四個領域皆已完成；目前共${cs.length}門。</div>`}</section>`}
function renderExternal(){const cs=recognized().filter(c=>c.external),total=cs.reduce((n,c)=>n+c.credits,0),used=Math.min(total,12),over=Math.max(0,total-12);externalSummary.innerHTML=`<section class="special-card external-card"><div><h3>外系學分認列</h3><p>外系課程最多認列12學分，超過部分不計入。</p>${over?`<p class="external-over">已超過${over}學分，超過部分不計入。</p>`:""}</div><div class="progress-total"><strong>${used}／12</strong><span>已認列學分${total>12?`（實修${total}）`:""}</span></div></section>`}
detailTabs.onclick=e=>{const b=e.target.closest("[data-tab]");if(!b)return;tab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));termFilter.closest("label").classList.toggle("hidden",tab==="unmatched");renderCourses()};termFilter.onchange=renderCourses;
function state(c){if(c.status==="done"||c.status==="classified")return["done",c.recognitionType==="exemption"?"已抵免／認證":"已完成",c.status==="classified"?`人工認列為${c.category}${c.external?"（外系）":""}`:""];if(c.status==="failed")return["failed","尚未完成",`曾於${c.attemptTerm}修習，但未通過`];if(c.status==="unmatched")return["pending","待人工分類",c.external?"外系課程，需人工確認認列類別":"時序表內找不到此課程"];return["missing","尚未修習",""]}
function renderCourses(){let list=student.courses;if(tab==="missing")list=list.filter(c=>["missing","failed"].includes(c.status));if(tab==="unmatched")list=list.filter(c=>c.status==="unmatched");else if(termFilter.value!=="all")list=list.filter(c=>c.term===termFilter.value);if(!list.length){courseContent.innerHTML='<div class="empty">目前沒有符合條件的課程。</div>';return}const groups=tab==="unmatched"?{"待人工分類":list}:list.reduce((o,c)=>((o[c.term]??=[]).push(c),o),{});courseContent.innerHTML=Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([term,cs])=>`<section class="term-section"><h3>${terms[term]||term}</h3><table class="course-table"><thead><tr><th>課程名稱</th><th>學分類別</th><th>學分</th><th>修課狀態</th>${role==="teacher"?"<th>操作</th>":""}</tr></thead><tbody>${cs.map(c=>{const[s,l,n]=state(c),cat=c.subCategory?`${c.category}｜${c.subCategory}`:(c.category||"尚未分類"),canAdjust=["done","classified","unmatched","missing"].includes(c.status),action=c.status==="missing"?"設定抵免／認證":(c.status==="unmatched"?"人工認列":"調整認列");return `<tr><td data-label="課程">${c.name}${c.adjusted?'<div class="audit-note">已人工調整認列</div>':""}</td><td data-label="類別">${cat}</td><td data-label="學分">${c.credits}</td><td data-label="狀態"><span class="status ${s}">${l}</span>${n?`<div class="course-note">${n}</div>`:""}</td>${role==="teacher"?`<td data-label="操作">${canAdjust?`<button class="action-link classify" data-id="${c.id}">${action}</button>`:"—"}</td>`:""}</tr>`}).join("")}</tbody></table></section>`).join("");document.querySelectorAll(".classify").forEach(b=>b.onclick=()=>openClassify(b.dataset.id))}
function openClassify(id){selected=student.courses.find(c=>c.id===id);selected.wasMissing=selected.status==="missing";classifyCourseName.textContent=`${selected.name}（${selected.credits}學分）${selected.wasMissing?"｜設定為抵免／認證":""}`;classificationCategory.value=selected.category||"專業選修";classificationExternal.checked=!!selected.external;classificationNote.value=selected.note||"";classifyDialog.showModal()}
saveClassification.onclick=()=>{if(!selected)return;if(classificationType.value==="excluded"){selected.status="excluded";selected.category=null}else{selected.status="classified";selected.category=classificationCategory.value;if(selected.wasMissing)selected.recognitionType="exemption"}selected.external=classificationExternal.checked;selected.note=classificationNote.value.trim();selected.adjusted=true;setTimeout(async()=>{render();tab="unmatched";document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab==="unmatched"));renderCourses();if(student.docId&&auth.currentUser){try{await updateDoc(doc(db,"students",student.docId),{courses:student.courses,updatedAt:serverTimestamp()})}catch(error){console.error(error);alert("畫面已調整，但儲存到 Firebase 失敗，請確認權限規則已發布。")}}},0)};
