import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, where, setDoc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),provider=new GoogleAuthProvider();
const AI_WORKER_URL="https://must-resource-ai.f00931-must.workers.dev";
let targets={"校必修":30,"院必修":18,"專業必修":47,"專業選修":33},currentCurriculum=null,curricula=[];
const domains=["人文領域","藝術領域","社會領域","自然領域"];
const gradeNames=["一","二","三","四","五","六","七","八"];
const terms=Object.fromEntries(gradeNames.flatMap((name,i)=>[[`${i+1}-1`,`${name}年級上學期`],[`${i+1}-2`,`${name}年級下學期`]]));
const termOptions=Object.entries(terms).map(([value,label])=>`<option value="${value}">${label}</option>`).join("");
transcriptTargetTerm.innerHTML='<option value="">請選擇年級／學期</option>'+termOptions;
classificationTerm.innerHTML=termOptions;
let currentAccess=null;
const normalizedEmail=value=>String(value||"").trim().toLowerCase();
const workspaceOwnerEmail=()=>currentAccess?.role==="assistant"?normalizedEmail(currentAccess.ownerEmail):normalizedEmail(currentAccess?.email||auth.currentUser?.email);
let student={id:"DEMO0001",name:"測試學生",department:"旅館管理與廚藝創意系",program:"日間部四技",admissionYear:"115",courses:[
 {id:"GE101",name:"分類通識-音樂好好聽(藝術領域)",credits:2,category:"校必修",subCategory:"分類通識",domain:"藝術領域",term:"1-1",status:"done"},
 {id:"PE101",name:"體育(一)",credits:2,category:"校必修",term:"1-1",status:"done"},{id:"CH101",name:"應用中文(一)",credits:2,category:"校必修",term:"1-1",status:"done"},
 {id:"EN101",name:"應用英文(一)",credits:2,category:"校必修",term:"1-1",status:"failed",attemptTerm:"115-1"},{id:"CS101",name:"程式設計概論",credits:2,category:"院必修",term:"1-1",status:"missing"},
 {id:"HC101",name:"旅館事業概論",credits:2,category:"專業必修",term:"1-1",status:"done"},{id:"HC102",name:"餐旅安全與法規",credits:2,category:"專業必修",term:"1-1",status:"done"},
 {id:"HC103",name:"餐飲廚藝概論",credits:2,category:"專業必修",term:"1-1",status:"done"},{id:"HC104",name:"餐旅美學",credits:2,category:"專業選修",term:"1-1",status:"done"},
 {id:"TO101",name:"觀光產業概論",credits:2,category:"專業選修",term:"1-1",status:"done"},{id:"GE102",name:"分類通識-創意邏輯動動手(自然領域)",credits:2,category:"校必修",subCategory:"分類通識",domain:"自然領域",term:"1-2",status:"done"},
 {id:"PE102",name:"體育(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},{id:"CH102",name:"應用中文(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},
 {id:"EN102",name:"應用英文(二)",credits:2,category:"校必修",term:"1-2",status:"missing"},{id:"AI101",name:"人工智慧概論",credits:2,category:"院必修",term:"1-2",status:"missing"},
 {id:"HC110",name:"房務管理",credits:2,category:"專業必修",term:"1-2",status:"missing"},{id:"HC111",name:"房務模擬實務",credits:2,category:"專業必修",term:"1-2",status:"missing"},
 {id:"X001",name:"國際禮儀",credits:2,category:"專業選修",term:"2-2",status:"done"},{id:"X002",name:"投資理財實務",credits:2,category:"專業選修",term:"2-1",status:"done"}
]};
const demoStudent=structuredClone(student);
let role="student",tab="timeline",selected=null,editingCurriculum=null,editingStudent=null;
const localCurriculumPdfs=new Map();
const views=[...document.querySelectorAll(".view")],recognized=()=>student.courses.filter(c=>c.status==="done"||c.status==="classified");
function show(id){views.forEach(v=>v.classList.toggle("hidden",v.id!==id));scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>show(b.dataset.back));
studentEntry.onclick=()=>show("queryView");teacherEntry.onclick=loginAndOpenTeacher;
addStudentBtn.onclick=async()=>{await loadCurricula();fillCurriculumSelect();if(!curricula.length){alert("請先建立至少一份時序表。");curriculumDialog.showModal();return}editingStudent=null;studentForm.reset();programInput.value="日間部四技";studentDialogTitle.textContent="新增學生";saveStudentBtn.textContent="新增學生";studentIdInput.disabled=false;studentDialog.showModal()};
curriculumBtn.onclick=async()=>{await loadCurricula();renderCurricula();curriculumDialog.showModal()};
queryForm.onsubmit=e=>{e.preventDefault();const ok=queryName.value.trim()===demoStudent.name&&queryStudentId.value.trim().toUpperCase()===demoStudent.id;queryError.textContent=ok?"":"學生查詢尚未連接正式資料；示範請使用測試學生／DEMO0001。";if(ok){student=structuredClone(demoStudent);openStudent("student")}};
logoutBtn.onclick=async()=>{await signOut(auth);show("homeView")};

async function loginAndOpenTeacher(){
 try{
  const user=auth.currentUser||(await signInWithPopup(auth,provider)).user;
  const accessSnap=await getDoc(doc(db,"authorizedUsers",normalizedEmail(user.email)));
  if(!accessSnap.exists()||accessSnap.data().enabled===false){await signOut(auth);alert("此帳號尚未被加入老師／小幫手權限名單。");return}
  currentAccess=accessSnap.data();show("teacherView");await loadCurricula();await loadMyStudents();
 }catch(error){console.error(error);alert(error.code==="auth/popup-closed-by-user"?"已取消登入。":"登入或讀取資料失敗，請確認 Firebase 權限規則已發布。");}
}
async function loadMyStudents(){
 studentList.innerHTML='<div class="loading-row">正在載入學生資料…</div>';
 const snapshot=await getDocs(query(collection(db,"students"),where("ownerEmail","==",workspaceOwnerEmail())));
 const rows=snapshot.docs.map(d=>({docId:d.id,...d.data()}));
 if(!rows.length){studentList.innerHTML='<div class="empty">目前尚未建立學生，請按右上角「新增學生」。</div>';return}
 studentList.innerHTML=rows.map((s,i)=>`<article class="student-row"><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.studentId)}｜${escapeHtml(s.department)}｜${escapeHtml(s.admissionYear)}學年度入學</p></div><div class="student-row-actions"><button class="primary open-real" data-index="${i}">查看學分</button><button class="small-button edit-student" data-index="${i}">修改</button><button class="small-button danger delete-student" data-index="${i}">刪除</button></div></article>`).join("");
 document.querySelectorAll(".open-real").forEach(b=>b.onclick=async()=>{student=rows[Number(b.dataset.index)];student.id=student.studentId;currentCurriculum=curricula.find(c=>c.docId===student.curriculumId)||null;if(currentCurriculum)targets=currentCurriculum.targets;student.courses=student.courses?.length?student.courses:structuredClone(currentCurriculum?.courses||[]);openStudent("teacher")});
 document.querySelectorAll(".edit-student").forEach(b=>b.onclick=()=>openStudentEditor(rows[Number(b.dataset.index)]));
 document.querySelectorAll(".delete-student").forEach(b=>b.onclick=()=>removeStudent(rows[Number(b.dataset.index)]));
}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}

saveStudentBtn.onclick=async e=>{
 e.preventDefault();studentFormError.textContent="";
 const user=auth.currentUser,id=studentIdInput.value.trim().toUpperCase();
 if(!user||!id){studentFormError.textContent="請完整填寫資料。";return}
 try{
  const ownerEmail=workspaceOwnerEmail(),workspaceId=ownerEmail.replace(/[^a-z0-9]/g,"_");
  const ref=editingStudent?doc(db,"students",editingStudent.docId):doc(db,"students",`${workspaceId}_${id}`);
  if(!editingStudent&&(await getDoc(ref)).exists()){studentFormError.textContent="這個學號已經建立。";return}
  const curriculum=curricula.find(c=>c.docId===curriculumSelect.value);if(!curriculum){studentFormError.textContent="請選擇適用時序表。";return}
  if(editingStudent){const changed=editingStudent.curriculumId!==curriculum.docId,oldCourses=editingStudent.courses||[],newCourses=changed?mergeCoursesForCurriculum(curriculum.courses||[],oldCourses):oldCourses;await updateDoc(ref,{name:studentNameInput.value.trim(),admissionYear:admissionYearInput.value.trim(),department:departmentInput.value.trim(),program:programInput.value.trim(),curriculumId:curriculum.docId,courses:newCourses,lastEditorEmail:normalizedEmail(user.email),updatedAt:serverTimestamp()})}else await setDoc(ref,{studentId:id,name:studentNameInput.value.trim(),admissionYear:admissionYearInput.value.trim(),department:departmentInput.value.trim(),program:programInput.value.trim(),curriculumId:curriculum.docId,ownerEmail,courses:structuredClone(curriculum.courses||[]),createdByEmail:normalizedEmail(user.email),lastEditorEmail:normalizedEmail(user.email),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
  studentDialog.close();studentForm.reset();programInput.value="日間部四技";await loadMyStudents();
 }catch(error){console.error(error);studentFormError.textContent="新增失敗，請先發布最新版 Firestore 規則。"}
};
function openStudentEditor(s){editingStudent=s;fillCurriculumSelect();studentDialogTitle.textContent="修改學生";saveStudentBtn.textContent="儲存修改";studentNameInput.value=s.name||"";studentIdInput.value=s.studentId||"";studentIdInput.disabled=true;admissionYearInput.value=s.admissionYear||"";departmentInput.value=s.department||"";programInput.value=s.program||"";curriculumSelect.value=s.curriculumId||"";studentDialog.showModal()}
async function removeStudent(s){if(!confirm(`確定刪除學生「${s.name}（${s.studentId}）」？此操作會一併刪除其學分檢核資料。`))return;try{await deleteDoc(doc(db,"students",s.docId));await loadMyStudents()}catch(error){console.error(error);alert("刪除失敗，請確認權限。")}}
function normalizedName(name){return String(name||"").replace(/[\s　()（）【】\[\]·・,，.。]/g,"").toLowerCase()}
function coreCourseName(name){return String(name||"").replace(/[（(][^）)]*[）)]/g,"").replace(/[\s　【】\[\]·・,，.。]/g,"").toLowerCase()}
function mergeCoursesForCurriculum(template,history){const remaining=[...history];const result=structuredClone(template).map(course=>{const i=remaining.findIndex(h=>normalizedName(h.name)===normalizedName(course.name));if(i<0)return course;const old=remaining.splice(i,1)[0];return{...course,status:old.status,attemptTerm:old.attemptTerm,recognitionType:old.recognitionType,adjusted:old.adjusted,note:old.note}});remaining.filter(c=>["done","classified","failed","unmatched"].includes(c.status)).forEach(c=>result.push({...c,status:c.status==="failed"?"failed":"unmatched",previousCategory:c.category,category:null,note:[c.note,"更換時序表後需重新確認"].filter(Boolean).join("；")}));return result}
onAuthStateChanged(auth,user=>{if(!user)currentAccess=null;logoutBtn.classList.toggle("hidden",!user);systemBadge.textContent=user?`已登入：${user.email}`:"Firebase測試版"});

async function loadCurricula(){const ref=collection(db,"curricula");if(currentAccess?.role==="admin"){const snap=await getDocs(ref);curricula=snap.docs.map(d=>({docId:d.id,...d.data()})).filter(c=>!c.ownerEmail||normalizedEmail(c.ownerEmail)===workspaceOwnerEmail())}else{const snap=await getDocs(query(ref,where("ownerEmail","==",workspaceOwnerEmail())));curricula=snap.docs.map(d=>({docId:d.id,...d.data()}))}curricula.sort((a,b)=>String(b.admissionYear).localeCompare(String(a.admissionYear)))}
function fillCurriculumSelect(){curriculumSelect.innerHTML='<option value="">請選擇時序表</option>'+curricula.filter(c=>c.status==="ready").map(c=>`<option value="${c.docId}">${escapeHtml(c.admissionYear)}｜${escapeHtml(c.department)}｜${escapeHtml(c.program)}</option>`).join("")}
function renderCurricula(){curriculumList.innerHTML=curricula.length?curricula.map(c=>`<div class="curriculum-row"><div><strong>${escapeHtml(c.admissionYear)}學年度｜${escapeHtml(c.department)}｜${escapeHtml(c.program)}</strong><span>來源：${escapeHtml(c.sourceFileName||"未上傳")}｜課程${c.courses?.length||0}門${c.ownerEmail?"":"｜舊版資料，儲存後歸入我的工作區"}</span></div><div class="curriculum-actions"><span class="status-chip ${c.status==="ready"?"ready":"pending"}">${c.status==="ready"?"已啟用":"待辨識"}</span><button type="button" class="small-button edit-curriculum" data-id="${c.docId}">課程確認</button>${c.status!=="ready"?`<button type="button" class="small-button replace-curriculum" data-id="${c.docId}">更換PDF</button><button type="button" class="small-button danger delete-curriculum" data-id="${c.docId}">刪除</button>`:""}</div></div>`).join(""):'<div class="empty">你的工作區尚未建立時序表。</div>';document.querySelectorAll(".edit-curriculum").forEach(b=>b.onclick=()=>openCourseEditor(b.dataset.id));document.querySelectorAll(".replace-curriculum").forEach(b=>b.onclick=()=>replaceCurriculumPdf(b.dataset.id));document.querySelectorAll(".delete-curriculum").forEach(b=>b.onclick=()=>removeCurriculum(b.dataset.id))}
saveCurriculumBtn.onclick=async e=>{e.preventDefault();curriculumError.textContent="";try{const year=curriculumYear.value.trim(),department=curriculumDepartment.value.trim(),program=curriculumProgram.value.trim(),file=curriculumPdfInput.files[0];if(!year||!department||!program||!file){curriculumError.textContent="請完整填寫版本資料並選擇PDF。";return}if(file.type!=="application/pdf"){curriculumError.textContent="只接受PDF檔案。";return}const duplicate=curricula.some(c=>c.ownerEmail===workspaceOwnerEmail()&&c.admissionYear===year&&c.department===department&&c.program===program);if(duplicate){curriculumError.textContent="你的工作區已有相同入學年度、科系與學制的時序表。";return}const curriculumTargets={"校必修":Number(schoolRequiredInput.value),"院必修":Number(collegeRequiredInput.value),"專業必修":Number(majorRequiredInput.value),"專業選修":Number(majorElectiveInput.value)},id=`${workspaceOwnerEmail().replace(/[^a-z0-9]/g,"_")}_${year}_${Date.now()}`;saveCurriculumBtn.disabled=true;saveCurriculumBtn.textContent="建立中…";await setDoc(doc(db,"curricula",id),{admissionYear:year,department,program,totalCredits:Number(totalCreditsInput.value),targets:curriculumTargets,courses:[],status:"pending",sourceFileName:file.name,sourceStored:false,ownerEmail:workspaceOwnerEmail(),createdByEmail:normalizedEmail(auth.currentUser?.email),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});localCurriculumPdfs.set(id,file);await loadCurricula();renderCurricula();fillCurriculumSelect();openCourseEditor(id);await parseCurriculumWithAI()}catch(error){console.error(error);curriculumError.textContent="建立失敗，請確認Firestore規則已發布。"}finally{saveCurriculumBtn.disabled=false;saveCurriculumBtn.textContent="選取PDF並建立待辨識版本"}};
function openCourseEditor(id){editingCurriculum=curricula.find(c=>c.docId===id);if(!editingCurriculum)return;courseEditorTitle.textContent=`${editingCurriculum.admissionYear}｜${editingCurriculum.department}｜${editingCurriculum.program}`;courseImportText.value=(editingCurriculum.courses||[]).map(c=>`${c.term}｜${c.category}｜${c.name}｜${c.credits}`).join("\n");courseEditorError.textContent="";courseEditorDialog.showModal()}
async function replaceCurriculumPdf(id){const curriculum=curricula.find(c=>c.docId===id);if(!curriculum)return;const input=document.createElement("input");input.type="file";input.accept="application/pdf";input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.type!=="application/pdf"){alert("只接受PDF檔案。");return}try{await updateDoc(doc(db,"curricula",id),{sourceFileName:file.name,sourceStored:false,courses:[],status:"pending",updatedAt:serverTimestamp()});localCurriculumPdfs.set(id,file);await loadCurricula();renderCurricula();openCourseEditor(id);await parseCurriculumWithAI()}catch(error){console.error(error);alert("更換失敗，請確認Firestore規則已發布。")}};input.click()}
async function removeCurriculum(id){const curriculum=curricula.find(c=>c.docId===id);if(!curriculum||!confirm(`確定刪除「${curriculum.admissionYear}｜${curriculum.department}｜${curriculum.program}」？`))return;try{const used=await getDocs(query(collection(db,"students"),where("ownerEmail","==",workspaceOwnerEmail()),where("curriculumId","==",id)));if(!used.empty){alert("這份時序表已經綁定學生，不能刪除。請改用課程修改或建立新版本。");return}await deleteDoc(doc(db,"curricula",id));await loadCurricula();renderCurricula();fillCurriculumSelect()}catch(error){console.error(error);alert("刪除失敗，請確認權限及 Firestore 索引已建立。")}}
confirmCoursesBtn.onclick=async e=>{e.preventDefault();try{const allowed=new Set(Object.keys(targets)),lines=courseImportText.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),courses=lines.map((line,i)=>{const p=line.split(/[｜|]/).map(x=>x.trim());if(p.length!==4||!terms[p[0]]||!allowed.has(p[1])||!p[2]||!(Number(p[3])>0))throw new Error(`第${i+1}行格式錯誤`);const name=p[2],domain=(name.match(/\((人文|藝術|社會|自然)領域\)/)||[])[1];return{id:`C${i+1}`,term:p[0],category:p[1],name,credits:Number(p[3]),status:"missing",...(name.startsWith("分類通識-")?{subCategory:"分類通識",domain:domain?`${domain}領域`:null}:{})}});if(!courses.length)throw new Error("請至少建立一門課程");await updateDoc(doc(db,"curricula",editingCurriculum.docId),{courses,targets:editingCurriculum.targets||targets,totalCredits:editingCurriculum.totalCredits||Object.values(editingCurriculum.targets||targets).reduce((a,b)=>a+b,0),status:"ready",ownerEmail:editingCurriculum.ownerEmail||workspaceOwnerEmail(),updatedAt:serverTimestamp()});courseEditorDialog.close();await loadCurricula();renderCurricula();fillCurriculumSelect()}catch(error){courseEditorError.textContent=error.message||"課程儲存失敗。"}};
aiParseBtn.onclick=parseCurriculumWithAI;
async function parseCurriculumWithAI(){const file=localCurriculumPdfs.get(editingCurriculum?.docId);if(!file){courseEditorError.textContent="請先按「更換PDF」重新選擇原始時序表。";return}aiParseBtn.disabled=true;aiParseBtn.textContent="AI辨識中…";courseEditorError.textContent="正在將PDF轉為圖片並辨識，請稍候。";try{const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;if(pdf.numPages>4)throw new Error("目前最多辨識4頁PDF");const images=[];for(let pageNo=1;pageNo<=pdf.numPages;pageNo++){const page=await pdf.getPage(pageNo),viewport=page.getViewport({scale:1.8}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise;images.push({mimeType:"image/jpeg",data:canvas.toDataURL("image/jpeg",.88).split(",")[1]})}const response=await fetch(`${AI_WORKER_URL}/ai/curriculum-parse`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({images})}),result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"AI辨識失敗");const c=result.curriculum;editingCurriculum.targets=c.targets;editingCurriculum.totalCredits=c.totalCredits;courseImportText.value=c.courses.map(x=>`${x.term}｜${x.category}｜${x.name}｜${x.credits}`).join("\n");courseEditorError.textContent=c.warnings?.length?`AI已完成，請特別核對：${c.warnings.join("；")}`:`AI已完成，共辨識${c.courses.length}門課程，請核對後再啟用。`}catch(error){console.error(error);courseEditorError.textContent=error.message||"AI辨識失敗，請稍後再試。"}finally{aiParseBtn.disabled=false;aiParseBtn.textContent="AI自動辨識"}}
let pastedTranscriptImage=null,pastedTranscriptUrl="";
importTranscriptBtn.onclick=()=>{clearTranscriptPaste();transcriptTargetTerm.value="";transcriptPasteDialog.showModal();setTimeout(()=>transcriptTargetTerm.focus(),50)};
transcriptPasteDialog.addEventListener("paste",e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith("image/"));if(!item){transcriptPasteError.textContent="剪貼簿裡沒有圖片，請先截圖再按 Ctrl＋V。";return}e.preventDefault();const file=item.getAsFile();if(!file)return;pastedTranscriptImage=file;if(pastedTranscriptUrl)URL.revokeObjectURL(pastedTranscriptUrl);pastedTranscriptUrl=URL.createObjectURL(file);transcriptPreview.src=pastedTranscriptUrl;transcriptPreview.classList.remove("hidden");transcriptPasteZone.querySelector("strong").textContent="已貼上成績截圖";transcriptPasteZone.querySelector("span").textContent="確認畫面清楚後，按下AI辨識";transcriptPasteError.textContent="";analyzeTranscriptBtn.disabled=false;clearTranscriptImageBtn.disabled=false});
clearTranscriptImageBtn.onclick=clearTranscriptPaste;
analyzeTranscriptBtn.onclick=()=>{if(!transcriptTargetTerm.value){transcriptPasteError.textContent="請先選擇這張成績所屬的年級／學期。";transcriptTargetTerm.focus();return}if(pastedTranscriptImage)parseTranscript(pastedTranscriptImage)};
function clearTranscriptPaste(){pastedTranscriptImage=null;if(pastedTranscriptUrl)URL.revokeObjectURL(pastedTranscriptUrl);pastedTranscriptUrl="";transcriptPreview.removeAttribute("src");transcriptPreview.classList.add("hidden");transcriptPasteZone.querySelector("strong").textContent="請在這裡貼上成績截圖";transcriptPasteZone.querySelector("span").textContent="先點一下此區域，再按 Ctrl＋V";transcriptPasteError.textContent="";analyzeTranscriptBtn.disabled=true;clearTranscriptImageBtn.disabled=true}
async function fileToImages(file){if(file.type.startsWith("image/")){return[{mimeType:file.type,data:(await fileToDataUrl(file)).split(",")[1]}]}const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;if(pdf.numPages>6)throw new Error("目前一次最多辨識6頁成績資料");const images=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),viewport=page.getViewport({scale:1.8}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise;images.push({mimeType:"image/jpeg",data:canvas.toDataURL("image/jpeg",.88).split(",")[1]})}return images}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
async function parseTranscript(file){analyzeTranscriptBtn.disabled=true;analyzeTranscriptBtn.textContent="AI辨識中…";transcriptPasteError.textContent="正在辨識課程，請稍候。";try{const images=await fileToImages(file),response=await fetch(`${AI_WORKER_URL}/ai/transcript-parse`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({images})}),result=await response.json();if(!response.ok||!result.success)throw new Error(result.error||"歷史成績辨識失敗");applyTranscript(result.transcript,transcriptTargetTerm.value);await updateDoc(doc(db,"students",student.docId),{courses:student.courses,lastEditorEmail:normalizedEmail(auth.currentUser?.email),updatedAt:serverTimestamp()});render();transcriptPasteDialog.close();alert(`完成：已依「${terms[transcriptTargetTerm.value]}」比對${result.transcript.courses.length}門課程。時序表外課程已放入待人工分類。`)}catch(error){console.error(error);transcriptPasteError.textContent=error.message||"歷史成績辨識失敗，請確認Worker已更新。"}finally{analyzeTranscriptBtn.disabled=!pastedTranscriptImage;analyzeTranscriptBtn.textContent="AI辨識成績"}}
function transcriptMatchIndex(itemName,targetTerm){const candidates=student.courses.map((course,index)=>({course,index})).filter(x=>x.course.term===targetTerm);const exact=candidates.find(x=>normalizedName(x.course.name)===normalizedName(itemName));if(exact)return exact.index;const core=coreCourseName(itemName),similar=candidates.filter(x=>{const c=coreCourseName(x.course.name);return c===core||c.includes(core)||core.includes(c)});return similar.length===1?similar[0].index:-1}
function applyTranscript(data,targetTerm){for(const item of data.courses){const index=item.external?-1:transcriptMatchIndex(item.name,targetTerm),attemptTerm=item.academicTerm||data.academicTerm||terms[targetTerm];if(index>=0){const old=student.courses[index];student.courses[index]={...old,status:item.passed?"done":"failed",attemptTerm}}else student.courses.push({id:`H${Date.now()}${Math.random()}`,name:item.name,credits:item.credits,term:targetTerm,category:null,status:"unmatched",passed:item.passed,attemptTerm,external:!!item.external,note:item.external?"成績資料標示外系":`${terms[targetTerm]}的時序表內找不到此課程`})}}
function openStudent(r){role=r;tab="timeline";document.querySelectorAll(".teacher-only").forEach(e=>e.classList.toggle("hidden",r!=="teacher"));document.querySelectorAll(".tab").forEach(e=>e.classList.toggle("active",e.dataset.tab==="timeline"));termFilter.value="all";detailBack.onclick=()=>show(r==="teacher"?"teacherView":"queryView");render();show("detailView")}
function totals(){const out=Object.fromEntries(Object.keys(targets).map(k=>[k,0]));let ext=0;recognized().forEach(c=>{let value=c.credits;if(c.external){value=Math.max(0,Math.min(value,12-ext));ext+=value}if(c.category in out)out[c.category]+=value});return out}
function render(){const t=totals(),sum=Object.values(t).reduce((a,b)=>a+b,0);studentHeader.innerHTML=`<div><h2>${student.name}</h2><p>${student.id}｜${student.department}｜${student.program}｜${student.admissionYear}學年度入學</p></div><div class="progress-total"><span>目前已取得</span><strong>${sum} 學分</strong></div>`;creditSummary.innerHTML=Object.entries(targets).map(([n,max])=>`<article class="credit-card"><h3>${n}</h3><div class="credit-numbers"><strong>${t[n]}</strong><span>／${max} 學分</span></div><div class="meter"><span style="width:${Math.min(100,t[n]/max*100)}%"></span></div></article>`).join("");renderGeneral();renderExternal();renderCourses()}
function renderGeneral(){const cs=recognized().filter(c=>c.subCategory==="分類通識"),credits=cs.reduce((n,c)=>n+c.credits,0),missing=domains.filter(d=>!cs.some(c=>c.domain===d));generalEducationSummary.innerHTML=`<section class="special-card"><div class="special-heading"><div><h3>分類通識領域檢核</h3><small>併入校必修；四領域各至少1門，再任選2門</small></div><strong>${credits}／12 學分</strong></div><div class="domain-grid">${domains.map(d=>{const count=cs.filter(c=>c.domain===d).length;return `<div class="domain-item ${count?"done":"missing"}"><strong>${d}</strong><span>${count?`已完成 ${count} 門`:"尚未完成"}</span></div>`}).join("")}</div>${missing.length?`<div class="warning-box">⚠ 尚缺領域：${missing.join("、")}</div>`:`<div class="success-box">✓ 四個領域皆已完成；目前共${cs.length}門。</div>`}</section>`}
function renderExternal(){const cs=recognized().filter(c=>c.external),total=cs.reduce((n,c)=>n+c.credits,0),used=Math.min(total,12),over=Math.max(0,total-12);externalSummary.innerHTML=`<section class="special-card external-card"><div><h3>外系學分認列</h3><p>外系課程最多認列12學分，超過部分不計入。</p>${over?`<p class="external-over">已超過${over}學分，超過部分不計入。</p>`:""}</div><div class="progress-total"><strong>${used}／12</strong><span>已認列學分${total>12?`（實修${total}）`:""}</span></div></section>`}
detailTabs.onclick=e=>{const b=e.target.closest("[data-tab]");if(!b)return;tab=b.dataset.tab;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));termFilter.closest("label").classList.toggle("hidden",tab==="unmatched");renderCourses()};termFilter.onchange=renderCourses;
function state(c){if(c.status==="done"||c.status==="classified")return["done",c.recognitionType==="exemption"?"已抵免／認證":"已完成",c.status==="classified"?`人工認列為${c.category}${c.external?"（外系）":""}`:""];if(c.status==="failed")return["failed","尚未完成",`曾於${c.attemptTerm}修習，但未通過`];if(c.status==="unmatched")return["pending","待人工分類",c.external?"外系課程，需人工確認認列類別":"時序表內找不到此課程"];return["missing","尚未修習",""]}
function renderCourses(){let list=student.courses;if(tab==="missing")list=list.filter(c=>["missing","failed"].includes(c.status));if(tab==="unmatched")list=list.filter(c=>c.status==="unmatched");else if(termFilter.value!=="all")list=list.filter(c=>c.term===termFilter.value);if(!list.length){courseContent.innerHTML='<div class="empty">目前沒有符合條件的課程。</div>';return}const groups=tab==="unmatched"?{"待人工分類":list}:list.reduce((o,c)=>((o[c.term]??=[]).push(c),o),{});courseContent.innerHTML=Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([term,cs])=>`<section class="term-section"><h3>${terms[term]||term}</h3><table class="course-table"><thead><tr><th>課程名稱</th><th>學分類別</th><th>學分</th><th>修課狀態</th>${role==="teacher"?"<th>操作</th>":""}</tr></thead><tbody>${cs.map(c=>{const[s,l,n]=state(c),cat=c.subCategory?`${c.category}｜${c.subCategory}${c.domain?`（${c.domain}）`:""}`:(c.category||"尚未分類"),canAdjust=["done","classified","unmatched","missing"].includes(c.status),action=c.status==="missing"?"設定抵免／認證":(c.status==="unmatched"?"人工認列":"調整認列");return `<tr><td data-label="課程">${c.name}${c.adjusted?'<div class="audit-note">已人工調整認列</div>':""}</td><td data-label="類別">${cat}</td><td data-label="學分">${c.credits}</td><td data-label="狀態"><span class="status ${s}">${l}</span>${n?`<div class="course-note">${n}</div>`:""}</td>${role==="teacher"?`<td data-label="操作">${canAdjust?`<button class="action-link classify" data-id="${c.id}">${action}</button>`:"—"}</td>`:""}</tr>`}).join("")}</tbody></table></section>`).join("");document.querySelectorAll(".classify").forEach(b=>b.onclick=()=>openClassify(b.dataset.id))}
classificationCategory.onchange=()=>{const schoolRequired=classificationCategory.value==="校必修";classificationDomain.disabled=!schoolRequired;if(!schoolRequired)classificationDomain.value=""};
classificationDomain.onchange=()=>{if(classificationDomain.value)classificationCategory.value="校必修"};
classificationType.onchange=updateReplacementFields;
replacementCourse.onchange=()=>{const target=student.courses.find(c=>c.id===replacementCourse.value);if(!target)return;classificationCategory.value=target.category||"專業選修";const isGeneral=target.subCategory==="分類通識"||target.name.includes("分類通識");classificationDomain.disabled=!isGeneral;if(!isGeneral)classificationDomain.value=""};
function updateReplacementFields(){const replacing=classificationType.value==="replacement";replacementCourseLabel.classList.toggle("hidden",!replacing);replacementCourse.required=replacing;classificationTerm.disabled=replacing;const excluded=classificationType.value==="excluded";classificationCategory.disabled=excluded;classificationDomain.disabled=excluded||classificationCategory.value!=="校必修"}
function openClassify(id){selected=student.courses.find(c=>c.id===id);selected.wasMissing=selected.status==="missing";classifyCourseName.textContent=`${selected.name}（${selected.credits}學分）${selected.wasMissing?"｜設定為抵免／認證":""}`;classificationType.value="category";classificationCategory.value=selected.category||"專業選修";classificationDomain.value=selected.domain||"";classificationTerm.value=selected.term||"1-1";classificationExternal.checked=!!selected.external;classificationNote.value=selected.note||"";const candidates=student.courses.filter(c=>c!==selected&&["missing","failed"].includes(c.status));replacementCourse.innerHTML='<option value="">請選擇要替代的課程</option>'+candidates.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(terms[c.term]||c.term)}｜${escapeHtml(c.name)}｜${c.credits}學分</option>`).join("");updateReplacementFields();classifyDialog.showModal()}
saveClassification.onclick=e=>{if(!selected)return;if(classificationType.value==="replacement"&&!replacementCourse.value){e.preventDefault();alert("請選擇要替代的時序表課程。");return}if(classificationType.value==="excluded"){selected.status="excluded";selected.category=null;selected.term=classificationTerm.value;delete selected.subCategory;delete selected.domain}else if(classificationType.value==="replacement"){const target=student.courses.find(c=>c.id===replacementCourse.value);if(!target)return;const actualName=selected.name,originalName=target.name;Object.assign(target,{status:"classified",name:actualName,originalRequirement:originalName,category:classificationDomain.value?"校必修":classificationCategory.value,external:classificationExternal.checked,note:[classificationNote.value.trim(),`替代時序表課程：${originalName}`].filter(Boolean).join("；"),adjusted:true,recognitionType:"replacement",attemptTerm:selected.attemptTerm});if(classificationDomain.value){target.subCategory="分類通識";target.domain=classificationDomain.value}else{delete target.subCategory;delete target.domain}student.courses=student.courses.filter(c=>c!==selected)}else{selected.status="classified";selected.category=classificationCategory.value;selected.term=classificationTerm.value;if(classificationDomain.value){selected.category="校必修";selected.subCategory="分類通識";selected.domain=classificationDomain.value}else{delete selected.subCategory;delete selected.domain}if(selected.wasMissing)selected.recognitionType="exemption";selected.external=classificationExternal.checked;selected.note=classificationNote.value.trim();selected.adjusted=true}setTimeout(async()=>{render();tab="unmatched";document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab==="unmatched"));renderCourses();if(student.docId&&auth.currentUser){try{await updateDoc(doc(db,"students",student.docId),{courses:student.courses,lastEditorEmail:normalizedEmail(auth.currentUser.email),updatedAt:serverTimestamp()})}catch(error){console.error(error);alert("畫面已調整，但儲存到 Firebase 失敗，請確認權限規則已發布。")}}},0)};
